### ISSUE TITLE
[Question] Incorrect version in changelog, if using custom changelog generator

### ISSUE THREAD

**Issue by Kristinita** [webpro/release-it#218] opened 2018-01-25 12:45 UTC
### 1. Summary

If I use [**npm generate-changelog**](https://www.npmjs.com/package/generate-changelog) for changelog generating, previous version show in [**release page**](https://github.com/Kristinita/SashaBranchReleaseIt/releases).

![Previous release](https://i.imgur.com/Vax00iP.png)

#### 2.1. Environment

+ Windows 10 Enterprise LTSB 64-bit EN,
+ git 2.16.0.windows.2,
+ Node.js 9.4.0,
+ release-it 6.1.1,
+ generate-changelog 1.7.0.

#### 2.2. Configuration

Part of my [**my example GitHub repository**](https://github.com/Kristinita/SashaBranchReleaseIt):

`.release-it.json`:

```json
{
    "buildCommand": "changelog",
    "changelogCommand": "changelog ${version} -f -",
    "github": {
        "release": true,
        "tokenRef": "GITHUB_TOKEN"
    },
    "src": {
        "tagName": "st3-%s"
    }
}
```

`package.json`:

```json
{
  "name": "testing release-it",
  "version": "1.0.19",
  "scripts": {
    "release": "release-it"
  }
}
```

### 3. Steps to reproduce

+ I push any commit to repository,
+ I run command `release-it --no-npm.publish -n -V`.

```bash
D:\SashaBranchReleaseIt>git add .
warning: LF will be replaced by CRLF in CHANGELOG.MD.
The file will have its original line endings in your working directory.

D:\SashaBranchReleaseIt>git cz
cz-cli@2.9.6, cz-conventional-changelog@1.2.0


Line 1 will be cropped at 100 characters. All other lines will be wrapped after 100 characters.

? Select the type of change that you're committing: build:    Changes that affect the build system or external dependencies (example scopes: gulp,  broccoli, npm)
? Denote the scope of this change ($location, $browser, $compile, etc.):
 release-it
? Write a short, imperative tense description of the change:
 Demonstration commit
? Provide a longer description of the change:

? List any breaking changes or issues closed by this change:

[master a564d77] build(release-it): Demonstration commit
 1 file changed, 2 insertions(+), 1 deletion(-)

D:\SashaBranchReleaseIt>git push origin master
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 708 bytes | 50.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/Kristinita/SashaBranchReleaseIt.git
   f1c7b82..a564d77  master -> master

D:\SashaBranchReleaseIt>release-it --no-npm.publish -n -V
$ git rev-parse --git-dir
.git
$ git config --get remote.origin.url
https://github.com/Kristinita/SashaBranchReleaseIt.git
$ git diff-index --name-only HEAD --exit-code
$ git rev-parse --abbrev-ref --symbolic-full-name @{u}
origin/master
$ git describe --tags --abbrev=0
st3-1.0.18
$ changelog 1.0.19 -f -
#### 1.0.18 (2018-01-25)

##### Build System / Dependencies

* **release-it:**  Demonstration commit (a564d770)


$ bump package.json 1.0.19
$ changelog
$ git add package.json
warning: LF will be replaced by CRLF in package.json.
The file will have its original line endings in your working directory.
$ git add . --all
warning: LF will be replaced by CRLF in CHANGELOG.MD.
The file will have its original line endings in your working directory.
$ git status --short --untracked-files=no
M  CHANGELOG.MD
M  package.json
$ git commit --message="Release 1.0.19"
[master 19f740c] Release 1.0.19
 2 files changed, 7 insertions(+), 1 deletion(-)
$ git tag --annotate --message="Release 1.0.19" st3-1.0.19
$ git push --follow-tags
To https://github.com/Kristinita/SashaBranchReleaseIt.git
   a564d77..19f740c  master -> master
 * [new tag]         st3-1.0.19 -> st3-1.0.19
$ node-github releases#createRelease
node-github releases#createRelease: done (https://api.github.com/repos/Kristinita/SashaBranchReleaseIt/releases/9383970 st3-1.0.19 "Release 1.0.19")
```

### 4. Expected behavior

`buildCommand` generate the [**new version as expected**](https://github.com/Kristinita/SashaBranchReleaseIt/commit/19f740c70a72330ca67a229e1b9f5250abb34daa).

![buildCommand](https://i.imgur.com/Nk185Wb.png)

### 5. Actual behavior

`changelogCommand` generate [**previous version**](https://github.com/Kristinita/SashaBranchReleaseIt/releases):

![Previous release](https://i.imgur.com/Vax00iP.png)

### 6. Possible solution

Part of output:

```bash
$ changelog 1.0.19 -f -
#### 1.0.18 (2018-01-25)

##### Build System / Dependencies

* **release-it:**  Demonstration commit (a564d770)


$ bump package.json 1.0.19
$ changelog
```

Possibly, I need to run `bump package.json ${version}` earlier than the `changelogCommand`.

### 7. Not helped

See my [**latest commits**](https://github.com/Kristinita/SashaBranchReleaseIt/commits/master). For example, I try:

1. add parameters [**`"saveBump: false"` or `"saveBump: true"`**](https://www.npmjs.com/package/release-it#generate-custom-changelog),
1. add `bump package.json ${version}` to `"beforeChangelogCommand"`. I get output in console:

    > 'bump' is not recognized as an internal or external command,
operable program or batch file.

    I don't find, how I can use `bump` command in Windows.

Thanks.

**Comment by webpro** [comment] 2018-01-25 13:31
The `"safeBump": true` option is indeed what you need here. This will bump the version in `package.json` before `beforeChangelogCommand` and `changelogCommand` are executed.

There is no need to manually use `bump`, release-it does this for you.

**Comment by Kristinita** [comment] 2018-01-25 14:19
> The "safeBump": false option is indeed what you need here.

Thanks, it works!

I get incorrect result, because I test release-it with `--dry-run` option.
Please, compare:

```bash
D:\SashaBranchReleaseIt>release-it --no-npm.publish -n -V --dry-run
$ git rev-parse --git-dir
.git
$ git config --get remote.origin.url
https://github.com/Kristinita/SashaBranchReleaseIt.git
$ git diff-index --name-only HEAD --exit-code
$ git rev-parse --abbrev-ref --symbolic-full-name @{u}
origin/master
$ git describe --tags --abbrev=0
st3-1.0.19
(not executed in dry run)
$ changelog 1.0.20 -f -
#### 1.0.19 (2018-01-25)

##### Build System / Dependencies

* **release-it:**
  *  Test safe bump — false again (9950ff14)
  *  Test github.host variable (9a6e87bb)
  *  Test host variable (02be12e1)


$ changelog 1.0.20
(not executed in dry run)
$ git add package.json
(not executed in dry run)
$ git add . --all
(not executed in dry run)
$ git status --short --untracked-files=no
$ git commit --message="Release 1.0.20"
(not executed in dry run)
$ git tag --annotate --message="Release 1.0.20" st3-1.0.20
(not executed in dry run)
$ git push --follow-tags
(not executed in dry run)
$ node-github releases#createRelease
(not executed in dry run)
```

```bash
D:\SashaBranchReleaseIt>release-it --no-npm.publish -n -V
$ git rev-parse --git-dir
.git
$ git config --get remote.origin.url
https://github.com/Kristinita/SashaBranchReleaseIt.git
$ git diff-index --name-only HEAD --exit-code
$ git rev-parse --abbrev-ref --symbolic-full-name @{u}
origin/master
$ git describe --tags --abbrev=0
st3-1.0.19
$ bump package.json 1.0.20
$ changelog 1.0.20 -f -
#### 1.0.20 (2018-01-25)

##### Build System / Dependencies

* **release-it:**
  *  Test safe bump — false again (9950ff14)
  *  Test github.host variable (9a6e87bb)
  *  Test host variable (02be12e1)


$ changelog 1.0.20
$ git add package.json
warning: LF will be replaced by CRLF in package.json.
The file will have its original line endings in your working directory.
$ git add . --all
warning: LF will be replaced by CRLF in CHANGELOG.MD.
The file will have its original line endings in your working directory.
$ git status --short --untracked-files=no
M  CHANGELOG.MD
M  package.json
$ git commit --message="Release 1.0.20"
[master 3685f9f] Release 1.0.20
 2 files changed, 10 insertions(+), 1 deletion(-)
$ git tag --annotate --message="Release 1.0.20" st3-1.0.20
$ git push --follow-tags
To https://github.com/Kristinita/SashaBranchReleaseIt.git
   9950ff1..3685f9f  master -> master
 * [new tag]         st3-1.0.20 -> st3-1.0.20
$ node-github releases#createRelease
node-github releases#createRelease: done (https://api.github.com/repos/Kristinita/SashaBranchReleaseIt/releases/9385528 st3-1.0.20 "Release 1.0.20")
```

I think, that it would be nice, if you add support `safeBump`, if user run release-it with `--dry-run` option.

Thanks.

**Comment by webpro** [comment] 2018-01-25 19:55
Not sure what exactly the issue is here.

What I can say is that, by default, the `changelogCommand` is marked as a read-only command. So it can also run in a dry run (the other command hooks are not executed in a dry run). However, in your configuration this is overridden (and is executed).

Not sure what you mean with your latest comment regarding `safeBump`. The file is not actually bumped by release-it in a dry run (but maybe it is by overriding changelog command?).

**Comment by Kristinita** [comment] 2018-01-26 06:45
**For** my configuration:

**If** `--dry-run`:

```bash
$ changelog 1.0.20 -f -
#### 1.0.19 (2018-01-25)

```

**else**:

```bash
$ changelog 1.0.20 -f -
#### 1.0.20 (2018-01-25)
```

> So it can also run in a dry run (the other command hooks are not executed in a dry run).

I think, it would be nice, if behavior with `--dry-run` = behavior without `--dry-run`.

**Or** at least specify in README, that `"safeBump": false` doesn't work in `--dry-run` mode.

Thanks.

**Comment by webpro** [comment] 2018-01-28 18:19
The behavior of using `--dry-run` _should not_ be the same as an actual release.

In a dry run, the version is not actually bumped, so `safeBump` is not relevant here: it doesn't matter when it does not bump.

I think the issue is that `changelogCommand` is considered read-only by release-it so it will also run in a dry-run. However, your custom `changelogCommand` is not a read-only command, right? That's why you see different behavior.

Maybe the custom command can be moved to `beforeChangelogCommand`, this would not execute the `changelog` command in a dry run.

Closing this, as I think it's not a bug in release-it. Feel free to discuss further, though.

**Closed by webpro** 2018-01-28 18:19 UTC

**Comment by Kristinita** [comment] 2018-01-28 18:22
@webpro ,

> **Or** at least specify in README, that `"safeBump": false` doesn't work in `--dry-run` mode.

Another release-it users can have this problem.

Thanks.

**Comment by webpro** [comment] 2018-01-28 18:26
Again, `safeBump` has nothing to do with dry runs.
