### ISSUE TITLE
Permission denied (publickey) during release if ssh-key has password

### ISSUE THREAD

**Issue by jgentes** [webpro/release-it#407] opened 2018-11-30 22:15 UTC
Thanks for creating this, it's super useful!

The 'npm run release minor' command works great if I remove the password from my `~/.ssh/id_rsa` key. If it has a password, the command fails with `Permission denied (publickey)`.

I was hoping it would prompt me for the password when it tries to push. Is this by design?

**Comment by webpro** [comment] 2018-12-03 12:22
Hi @jgentes!

To be sure, does this happen with `release-it minor` (not `npm-script`) in the `git push` task?

Could you please share logs when adding the `--verbose` CLI argument?

In any case, this path/case isn't featured yet in release-it. Happy to look into it, though.

**Comment by webpro** [comment] 2018-12-05 10:51
Somehow I can't reproduce your issue. I'm on a Mac, and made sure the Keychain has no related entries; idem dito in `~/.ssh/config`. With or without a passphrase, it just pushes. Any clues?

The only thing I can simulate is without a key at all, eventually resulting in a successful push:

```
? Push? Yes
Username for 'https://github.com': webpro
Password for 'https://webpro@github.com': 
```

**Comment by jgentes** [comment] 2018-12-05 13:04
Maybe try an ssh github endpoint rather than https, I think that would be
the difference

**Comment by webpro** [comment] 2018-12-05 13:34
Of course, thanks! Oversight on my end. With an ssh endpoint it asks for the passphrase:

```
? Push? Yes
Enter passphrase for key '/Users/lars/.ssh/id_rsa': 
```

Are you sure you're having the (correct) SSH key installed in your GitHub account? If I remove that, it does give the "Permission denied (publickey)" error.

**Comment by jgentes** [comment] 2018-12-05 13:38
Hmm, odd. Yeah, it works if I do a standard git push, so they key is
correct, and the issue seems to be that I'm not even being prompted for the
password.

But if you're not seeing the issue maybe it's something on my end.
Personally I dont mind not having a password so it's not a huge issue for
me, I just didn't want to have to tell other people to remove their
passwords.

**Comment by webpro** [comment] 2018-12-05 14:09
Maybe it has something to do with users/rights on the OS level. E.g. is `release-it` executed as the same user as `git push` and `ssh-keygen`, etc.

I'm going to close this issue, as I would expect more people to report this or similar if it would be a release-it issue. Feel free to discuss further if there's anything that can be done on my end.

**Closed by webpro** 2018-12-05 14:09 UTC

**Comment by BlindKai** [comment] 2025-03-22 10:31
I believe that I have a similar problem.
I'm sure that I'm correctly typing the passphrase and that token has correct permissions on it.
It feels like passphrase cannot be typed it as we're in (Y/n) stage.

This is my `.release-it.json`
```json
{
  "$schema": "https://unpkg.com/release-it@18/schema/release-it.json",
  "git": {
    "commit": true,
    "commitMessage": "chore(release): ${version} [skip-ci]",
    "tag": true,
    "tagAnnotation": "${version}",
    "push": true
  },
  "npm": {
    "publish": false
  },
  "gitlab": {
    "release": true,
    "releaseName": "Release ${version}"
  },
  "plugins": {
    "@release-it/conventional-changelog": {
      "infile": "CHANGELOG.md",
      "preset": {
        "name": "conventionalcommits"
      }
    }
  }
}
```

And this is the output I'm getting while trying to execute the script:

```bash
❯ deno task release
Task release release-it --verbose
Enter passphrase for key '<path to key>': 

🚀 Let's release <repo> (0.0.0...0.1.0)

✔ Commit (chore(release): 0.1.0 [skip-ci])? Yes
✔ Tag (0.1.0)? Yes
✔ Push? Yes
Enter passphrase for key '<path to key>': 
Rolling back remote tag push 0.1.0
Enter passphrase for key '<path to key>': 
WARNING An error was encountered when trying to rollback the tag on the remote: error: unable to delete '0.1.0': remote ref does not exist
error: failed to push some refs to <path to repo>'

ERROR git@gitlab.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Rolling back changes...
Deleting local tag 0.1.0
Resetting local changes made
```
