### ISSUE TITLE
Push error

### ISSUE THREAD

**Issue by WaldoJeffers** [webpro/release-it#91] opened 2017-05-03 23:18 UTC
Hello,

Thanks for this great utility module.
I have this error when I try to use release-it in interactive mode:
`Please make sure an upstream remote repository is configured for the current branch`.
I answered yes at every question, the changes to package.json were commited, but the push was unsuccessful, the release was not created, and the module was not published to npm.

My GitHub token is exported as an environment variable, my upstream repo is correctly configured (I have no issues when I do regular a git push).

**Comment by webpro** [comment] 2017-05-04 08:26
Hi @WaldoJeffers, I think the error message included slightly more information. Did you configure both of these:

```
git remote add origin ${remoteUrl}
git push --set-upstream origin master
```

**Comment by WaldoJeffers** [comment] 2017-05-04 13:54
Hello @webpro,

Haha yes, you're right, I am sorry. I couldn't reach the full error message because it was too far in my console, and didn't want to try the command again because it creates new commits (and I couldn't reproduce the error with a dry run). Anyway, I set up a new repo where I can try everything and make random commits. Here's the full stack trace

```
Release source repo
? Show updated files? Yes
M  package.json

? Commit (Release 1.0.1)? Yes
? Tag (1.0.1)? Yes
? Push? Yes
ERROR Please make sure an upstream remote repository is configured for the current branch. Example commands:
git remote add origin git@github.com:WaldoJeffers/XXXXX.git
git push --set-upstream origin master
ERROR Error
    at run.catch.err (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\release-it\lib\git.js:127:11)
    at tryCatchReject (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\release-it\node_modules\when\lib\makePromise.js:845:30)
    at runContinuation1 (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\release-it\node_modules\when\lib\makePromise.js:804:4)
    at Rejected.when (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\release-it\node_modules\when\lib\makePromise.js:625:4)
    at Pending.run (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\release-it\node_modules\when\lib\makePromise.js:483:13)
    at Scheduler._drain (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\release-it\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\release-it\node_modules\when\lib\Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Yes, both of these are configured. Executing `git push` works fine, and running `git config --get remote.origin.url` returns `git@github.com:WaldoJeffers/XXXX.git`.


What other info should I provide ? I'm running on Windows, using an SSH key to push my code to GitHub, my GITHUB_TOKEN has the `repo` scope.

Thanks for your help.

**Comment by WaldoJeffers** [comment] 2017-05-05 10:28
Some updates about this issue: I think the problem comes from the fact that I need to enter my password for my SSH key when running `git push`. However, `shelljs` does not support [interactions in CLI](https://github.com/shelljs/shelljs/issues/716#issuecomment-299022822).

**Comment by webpro** [comment] 2017-05-05 13:54
Maybe these links are of help: https://github.com/webpro/release-it#ssh-keys--git-remotes

**Comment by webpro** [comment] 2017-05-16 12:37
Closing this issue (as I think the issue isn't in release-it). Feel free to re-open.

**Closed by webpro** 2017-05-16 12:37 UTC
Labels: invalid

**Comment by radamesh** [comment] 2023-03-15 20:45
`git push -u origin --all`

solve this problem
